Web/ViewModels/AvailabilitiesViewModel.cs
namespace Web.ViewModels;

public class AvailabilitiesViewModel
{
    public List<AvailabilityViewModel>? Availabilities { get; set; }
    
    

}

Web/ViewModels/AvailabilityViewModel.cs
using System.ComponentModel.DataAnnotations;
using Data.Enums;
using Utility.Extensions;

namespace Web.ViewModels;

public class AvailabilityViewModel : IValidatableObject
{
    public int Id { get; set; }
    public int EmployeeId { get; set; }
    public WeekDays DayOfWeek { get; set; }
    public TimeSpan? StartTime { get; set; }
    public TimeSpan? EndTime { get; set; }
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (StartTime.HasValue && EndTime.HasValue && StartTime.Value >= EndTime.Value && !StartTime.Value.IsMidnight() && !EndTime.Value.IsMidnight())
        {
            yield return new ValidationResult("End time must be greater than the start time.", new[] { nameof(EndTime) });
        }
    }


}

Web/Controllers/AvailabilityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Data.Repository;
using Data.Interfaces;
using Data.Models;
using Web.ViewModels;
using Data.Enums;
using System;
using Utility.Extensions;

namespace Web.Controllers;

[Authorize]
public class AvailabilityController : Controller
{
    private readonly IAvailabilityRepository _availabilityRepository;
    private readonly IEmployeeRepository _employeeRepository;

    public AvailabilityController(IAvailabilityRepository availabilityRepository,
        IEmployeeRepository employeeRepository)
    {
        _availabilityRepository = availabilityRepository;
        _employeeRepository = employeeRepository;
    }

    public IActionResult Index()
    {
        var loggedInEmployee = _employeeRepository.GetEmployeeByEmail(User.Identity.Name);
        
        // Check if the logged-in user is an employee
        // Get availabilities only for the logged-in employee
        var availabilities = _availabilityRepository.GetAvailabilitiesOfEmployee(loggedInEmployee.Id);
        
        var viewModel = new AvailabilitiesViewModel
        {
            Availabilities = availabilities.Select(a => new AvailabilityViewModel
            {
                Id = a.Id,
                EmployeeId = a.EmployeeId,
                DayOfWeek = a.DayOfWeek,
                StartTime = a.StartTime,
                EndTime = a.EndTime
            }).ToList()
        };

        return View(viewModel);
    }


    [HttpGet]
    public IActionResult EditCreate()
    {
        var loggedInEmployee = _employeeRepository.GetEmployeeByEmail(User.Identity.Name); //EmployeeId
        var excistingAvailabilities = _availabilityRepository.GetAvailabilitiesOfEmployee(loggedInEmployee.Id);
        List<Availability> availabilities = new List<Availability>();
        foreach (var day in Enum.GetValues(typeof(WeekDays)).Cast<WeekDays>())
        {
            var schoolHour = new Availability
            {
                DayOfWeek = day,
                EmployeeId = loggedInEmployee.Id
            };
            availabilities.Add(schoolHour);
        }

        // Merge the existing and  school hours dummys based on the day of the week
        List<Availability> mergedAvailabilities = excistingAvailabilities
            .Concat(availabilities)
            .GroupBy(sh => sh.DayOfWeek)
            .Select(group => group.First()).OrderBy(sh => sh.DayOfWeek)
            .ToList();

        var availabilitiesViewModels = mergedAvailabilities.Select(a => new AvailabilityViewModel
        {
            Id = a.Id,
            EmployeeId = a.EmployeeId,
            DayOfWeek = a.DayOfWeek,
            StartTime = a.StartTime,
            EndTime = a.EndTime
        }).ToList();


        var viewModel = new AvailabilitiesViewModel()
        {
            Availabilities = availabilitiesViewModels,
        };

        return View(viewModel);
    }


    // POST: HomeController/Edit/5
    [HttpPost]
    public IActionResult EditCreate(AvailabilitiesViewModel model)
    {
        if (ModelState.IsValid)
        {
            var nonZeroHours = model.Availabilities.Where(av => av.Id != 0).ToList();

            var zeroHoursLeft = nonZeroHours
                .Where(av => av.StartTime.Value.IsMidnight() || av.EndTime.Value.IsMidnight())
                .Select(av => new Availability
                {
                    Id = av.Id,
                    EmployeeId = av.EmployeeId,
                    DayOfWeek = av.DayOfWeek,
                    StartTime = (TimeSpan)av.StartTime,
                    EndTime = (TimeSpan)av.EndTime,
                }).ToList();

            // 0 hours means delete
            var existingHours = nonZeroHours
                .Where(av => !av.StartTime.Value.IsMidnight() && !av.EndTime.Value.IsMidnight())
                .Select(av => new Availability
                {
                    Id = av.Id,
                    EmployeeId = av.EmployeeId,
                    DayOfWeek = av.DayOfWeek,
                    StartTime = (TimeSpan)av.StartTime,
                    EndTime = (TimeSpan)av.EndTime,
                }).ToList();

            var newHours = model.Availabilities
                .Where(sh =>
                    sh.Id == 0 && sh.StartTime.HasValue && sh.EndTime.HasValue && !sh.StartTime.Value.IsMidnight() &&
                    !sh.EndTime.Value.IsMidnight())
                .Select(av => new Availability
                {
                    EmployeeId = av.EmployeeId,
                    DayOfWeek = av.DayOfWeek,
                    StartTime = (TimeSpan)av.StartTime,
                    EndTime = (TimeSpan)av.EndTime,
                }).ToList();

            // Delete SchoolHours
            _availabilityRepository.DeleteAvailabilities(zeroHoursLeft);
            // Update existing SchoolHours
            _availabilityRepository.UpdateAvailabilities(existingHours);
            // Create new SchoolHours
            _availabilityRepository.CreateAvailabilities(newHours);

            return RedirectToAction("Index");
        }

        return View(model);
    }
}

Web/Views/Availability/EditCreate.cshtml
@model Web.ViewModels.AvailabilitiesViewModel

@{
    ViewBag.Title = "Edit Availabilities";
    Layout = "_EmployeeLayout";
}

<div class="flex flex-col space-y-5">
    <div class="flex flex-col">
        <span class="font-bold text-xl">
            @if (Model.Availabilities != null && Model.Availabilities.Any())
            {
                <span>Bewerken</span>
            }
            else
            {
                <span>Toevoegen</span>
            }
        </span>
        <span class="text-sm text-gray-500">
        Vul hieronder uw beschikbaarheden in.
        </span>
    </div>

    <form asp-action="EditCreate" method="post" class="space-y-3">
        @for (var i = 0; i < Model.Availabilities.Count(); i++)
        {
            <input asp-for="@Model.Availabilities[i].Id" type="hidden" class="form-control"/>
            <input asp-for="@Model.Availabilities[i].EmployeeId" type="hidden" class="form-control"/>
            <input asp-for="@Model.Availabilities[i].DayOfWeek" type="hidden" class="form-control"/>
            <div class="form-control w-full">
                <div class="label">
                    <span class="label-text">
                        @Model.Availabilities[i].DayOfWeek
                    </span>
                </div>
                <div class="flex space-x-3 w-full">
                    <div class="w-1/2">
                        <label for="StartTime">Start Time:</label>
                        <input asp-for="@Model.Availabilities[i].StartTime" type="time" class="input w-full"/>
                        @Html.ValidationMessageFor(model => model.Availabilities[i].StartTime, "", new { @class = "text-danger" })
                    </div>
                    <div class="w-1/2">
                        <label for="EndTime">End Time:</label>
                        <input asp-for="@Model.Availabilities[i].EndTime" type="time" class="input w-full"/>
                        @Html.ValidationMessageFor(model => model.Availabilities[i].EndTime, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
        <button type="submit" class="btn btn-sm btn-primary mt-3 self-end">Opslaan</button>
    </form>
</div>

Web/Views/Availability/Index.cshtml
@model Web.ViewModels.AvailabilitiesViewModel

@{
    ViewBag.Title = "Beschikbaarheden";
    Layout = "_EmployeeLayout";
}

<div class="flex flex-col space-y-5">
    <div class="flex justify-between">
        <span class="font-bold text-xl">
            Beschikbaarheden
        </span>
        <a asp-controller="Availability" asp-action="EditCreate" class="btn btn-sm btn-primary">
            @if (Model.Availabilities != null && Model.Availabilities.Any())
            {
                <span>Bewerken</span>
            }
            else
            {
                <span>Toevoegen</span>
            }
        </a>
   
    </div>

    @if (Model.Availabilities != null && Model.Availabilities.Any())
    {
        @foreach (var availability in Model.Availabilities)
        {
            <div class="flex flex-col bg-gray-200 rounded p-3">
                <span class="font-semibold text-md">@availability.DayOfWeek</span>
                <span>Start: @availability.StartTime?.ToString("hh\\:mm")</span>
                <span>End: @availability.EndTime?.ToString("hh\\:mm")</span>
            </div>
        }
    }
    else
    {
        <p>Geen beschikbaarheden gevonden</p>
    }
</div>