Web/ViewModels/WorkedHoursViewModel.cs
namespace Web.ViewModels;

public class WorkedHoursViewModel
{
    public int WeekNumber { get; set; }
    public int CurrentWeekNumber { get; set; }
    public DateTime Date { get; set; }   
    public List<RegisteredHourViewModel> RegisteredHours { get; set; }
    
    public List<EmployeeViewModel> Employees { get; set; }
    public int[] SelectedHoursIds { get; set; }
    
    public bool AllWorkedHoursAreApproved { get; set; }
    

}

Web/Controllers/ExcelExportController.cs
using BusinessLogic.Services.HoursCalculationService;
using BusinessLogic.Services.HoursCalculationService.Factories;
using BusinessLogic.Services.HoursCalculationService.Interfaces;
using Data.Interfaces;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Utility.Extensions;

namespace Web.Controllers
{
    public class ExcelExportController : Controller
    {
        private readonly HoursCalculationManager hoursCalculationManager;
        private readonly IRegisteredHourRepository registeredHourRepository;
        public ExcelExportController(IRegisteredHourRepository registeredHourRepository)
        {
            this.registeredHourRepository = registeredHourRepository;
            this.hoursCalculationManager = new HoursCalculationManager(new HoursPolicyFactory());
        }
        public MemoryStream GetEmployeesHoursStream(IEnumerable<RegisteredHour> employeesHours, DateTime date)
        {
            var groupedHoursPerEmployee = employeesHours
                .GroupBy(rh => rh.EmployeeId)
                .Select(employeeGroup => new
                {
                    EmployeeId = employeeGroup.Key,
                    Employee = employeeGroup.First().Employee,
                    Charges = CalculateEmployeeHours(employeeGroup.ToList()) // Get hours for each employee
                })
                .OrderBy(entry => entry.EmployeeId)
                .ThenBy(entry => entry.Charges.Keys.First()) // Assuming EmployeeHours returns a dictionary with EmployeeId
                .ToList();

            var stream = new MemoryStream();

            using (var writeFile = new StreamWriter(stream, leaveOpen: true))
            {
                writeFile.WriteLine($"Jaar: {date.Year}; Week: {date.Week()}");
                writeFile.WriteLine($"EmployeeID;Naam;Uren;Toeslag") ;

                foreach (var employeeData in groupedHoursPerEmployee)
                {
                    var employeeName = $"{employeeData.Employee.FirstName} {employeeData.Employee.LastName}";
                    writeFile.WriteLine($"{employeeData.EmployeeId};{employeeName}");

                    foreach (var employeeHours in employeeData.Charges)
                    {
                        var charge = employeeHours.Key;
                        var totalWorkedHours = employeeHours.Value;

                        writeFile.WriteLine($";;{totalWorkedHours};{charge};");
                    }
                    writeFile.WriteLine();
                }
            }
            stream.Position = 0;
            return stream;
        }
        public Dictionary<int, decimal> CalculateEmployeeHours(List<RegisteredHour> hours)
        {
            List<Shift> shifts = new List<Shift>();

            foreach (RegisteredHour registeredHour in hours)
            {
                Shift shift = new Shift
                {
                    // Assuming EmployeeId is used for the corresponding property in Shift
                    EmployeeId = registeredHour.EmployeeId,
                    Start = registeredHour.Start,
                    End = registeredHour.End ?? registeredHour.Start, // Handle nullable End DateTime
                };
                shifts.Add(shift);
            }
            return hoursCalculationManager.CalculateHours(shifts);
        }

        public ActionResult DownloadExcel(DateTime date)
        {

            var registeredHours = registeredHourRepository.GetRegisteredHoursByDateRange(date.StartOfWeek(), date.EndOfWeek());

            var stream = GetEmployeesHoursStream(registeredHours, date);

            string fileName = $"Verloning-{date.Year}-Week{date.Week()}.csv";

            return File(stream, "application/octet-stream", fileName);
        }
    }
}

Web/Controllers/WorkedHoursController.cs
using Data.Enums;
using Data.Interfaces;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Utility.Extensions;
using Web.ViewModels;

namespace Web.Controllers;

public class WorkedHoursController : Controller
{

    private readonly IRegisteredHourRepository _registeredHourRepository;
    private readonly IShiftRepository _shiftRepository;
    private readonly IEmployeeRepository _employeeRepository;

    public WorkedHoursController(IRegisteredHourRepository registeredHourRepository, IShiftRepository shiftRepository,
        IEmployeeRepository employeeRepository)
    {
        _registeredHourRepository = registeredHourRepository;
        _shiftRepository = shiftRepository;
        _employeeRepository = employeeRepository;
    }

    public IActionResult Index(DateTime date, string? error, string? success)
    {
        var workedHours = _registeredHourRepository.GetRegisteredHoursByDate(date);
        var AllWorkedHoursInCurrentWeekAreApproved =
            _registeredHourRepository.GetRegisteredHoursByDateRange(date.StartOfWeek(), date.EndOfWeek());
        var shifts = _shiftRepository.GetDateShifts(date);
        if (error != null)
        {
            ModelState.AddModelError("", error);
        }
        if (success != null)
        {
            ModelState.AddModelError("", success);
        }

        WorkedHoursViewModel workedHoursViewModel = new WorkedHoursViewModel
        {
            WeekNumber = date.Week(),
            Date = date,
            RegisteredHours = workedHours.Select(rh => new RegisteredHourViewModel
            {
                Id = rh.Id,
                Employee = new EmployeeViewModel
                    { Id = rh.Employee.Id, FirstName = rh.Employee.FirstName, LastName = rh.Employee.LastName },
                Start = rh.Start,
                End = rh.End,
                Status = rh.Status,
                Shift = shifts.Where(shift => shift.EmployeeId == rh.EmployeeId).Select(shift => new ShiftViewModel
                {
                    Id = shift.Id,
                    Start = shift.Start,
                    End = shift.End,
                    Status = shift.Status,
                }).FirstOrDefault(),
            }).ToList(),
            Employees = _employeeRepository.GetAll().Select(e => new EmployeeViewModel
            {
                Id = e.Id,
                FirstName = e.FirstName,
                LastName = e.LastName,
            }).ToList(),
            AllWorkedHoursAreApproved = AllWorkedHoursInCurrentWeekAreApproved.All(rh => rh.Status == RegisteredHourStatus.Approved),
        };


        return View(workedHoursViewModel);
    }


    [HttpPost]
    public IActionResult Approve(WorkedHoursViewModel model, string type)
    {
        var registeredHours = new List<RegisteredHour>();
        var ApprodvedById = _employeeRepository.GetEmployeeByEmail(User.Identity.Name).Id;
        if (type == "everything")
        {
            var workedHours = _registeredHourRepository.GetRegisteredHoursByDate(model.Date);

            foreach (var workedHour in workedHours)
            {
                if (workedHour.End != null)
                {
                    workedHour.Status = RegisteredHourStatus.Approved;
                    workedHour.ApprovedById = ApprodvedById;
                    registeredHours.Add(workedHour);
                }

            }

            _registeredHourRepository.UpdateRange(registeredHours);

            if (workedHours.Count() != registeredHours.Count())
            {
                string message = "Some hours could not be approved because they do not have an end time.";
                return RedirectToAction("Index", "WorkedHours", new { date = model.Date, error = message });
            }
        }
        else
        {
            if (!ValidateSelectedHoursHaveEnd(model.SelectedHoursIds))
            {
                string message = "Some hours could not be approved because they do not have an end time.";
                return RedirectToAction("Index", "WorkedHours", new { date = model.Date, error = message });
            }

            foreach (var id in model.SelectedHoursIds)
            {
                var start = Request.Form["Start_" + id];
                var end = Request.Form["End_" + id];
                var updated = new RegisteredHour
                {
                    Id = id,
                    EmployeeId = int.TryParse(Request.Form["Employee_id" + id], out var employeeId) ? employeeId : 0,
                    Start = model.Date + DateTime.Parse(start).TimeOfDay,
                    End = model.Date + DateTime.Parse(end).TimeOfDay,
                    Status = RegisteredHourStatus.Approved,
                    ApprovedById = ApprodvedById
                };

                registeredHours.Add(updated);
            }

            _registeredHourRepository.UpdateRange(registeredHours);
        }


        return RedirectToAction("Index", "WorkedHours", new { date = model.Date });
    }

    private bool ValidateSelectedHoursHaveEnd(int[] selectedHourIds)
    {
        // Check if all selected hours have an end time
        foreach (var id in selectedHourIds)
        {
            var end = Request.Form["End_" + id];
            if (string.IsNullOrEmpty(end))
            {
                return false;
            }
        }

        return true;
    }

    [HttpPost]
    public IActionResult Create(CreateRegisteredHourViewModel model)
    {

        if (!ModelState.IsValid)
        {
            return RedirectToAction("Index", "WorkedHours", new { date = model.Date });
        }

        var registeredHour = new RegisteredHour
        {
            EmployeeId = model.EmployeeId,
            Start = model.Date.Date + model.Start,
            End = model.Date.Date + model.End,
            Status = RegisteredHourStatus.Approved,
        };

        _registeredHourRepository.Add(registeredHour);

        return RedirectToAction("Index", "WorkedHours", new { date = model.Date });
    }

    [HttpPost]
    public IActionResult Edit(RegisteredHourViewModel registeredHourViewModel)
    {
        var start = Request.Form["StartDate_" + registeredHourViewModel.Id];

        if (registeredHourViewModel.Start.TimeOfDay == null)
        {
            return RedirectToAction("Index", "WorkedHours", new { date = registeredHourViewModel.Start, error = "Starttijd kan niet leeg zijn"  });
        }
        
        registeredHourViewModel.Start = DateTime.Parse(start).Date + registeredHourViewModel.Start.TimeOfDay;
        
        if (registeredHourViewModel.End != null)
        {
            if(registeredHourViewModel.End.Value.TimeOfDay < registeredHourViewModel.Start.TimeOfDay)
            {
                registeredHourViewModel.End = DateTime.Parse(start).Date.AddDays(1) + registeredHourViewModel.End.Value.TimeOfDay;
            }
            else
            {
                registeredHourViewModel.End = DateTime.Parse(start).Date + registeredHourViewModel.End.Value.TimeOfDay;
            }
        }
        
        int? employeeId = registeredHourViewModel.Employee.Id;
        
        var registeredHour = new RegisteredHour
        { 
            Id = registeredHourViewModel.Id,
            EmployeeId = employeeId.Value,
            Start = registeredHourViewModel.Start,
            End = registeredHourViewModel.End,
            Status = registeredHourViewModel.Status,
        };
        
        _registeredHourRepository.Update(registeredHour);

        return RedirectToAction("Index", "WorkedHours", new { date = registeredHour.Start, success = "Tijdregistratie succesvol bijgewerkt"  });
    }
} 

Web/Views/WorkedHours/Index.cshtml
@using Web.ViewModels
@model Web.ViewModels.WorkedHoursViewModel

@{
    ViewData["Title"] = "Geklokte uren";
}


<span class="font-bold text-2xl">
    Urenregistratie
</span>

<div class="flex space-x-4">
    <div class="flex flex-col space-y-5 w-3/4 bg-base-200 p-5 rounded mt-3 h-screen">
        <span class="font-bold text-xl">
            Gewerkte uren
        </span>
        <form asp-action="Approve" method="post">
            <input type="hidden" name="Date" value="@Model.Date"/>
            <div class="flex justify-between py-5">
                @Html.Partial("Partials/_DaySelector")
                <div>
                    <button type="submit" name="type" value="selected" class="btn btn-sm btn-success rounded hidden" id="active">
                        <i class="fa-solid fa-check"></i>Geselecteerde uren Goedkeuren
                    </button>
                    <a class="btn btn-sm btn-disabled rounded" id="disabled">
                        <i class="fa-solid fa-check"></i>Geselecteerde uren Goedkeuren
                    </a>
                    <button type="submit" name="type" value="everything" class="btn btn-sm btn-success rounded">
                        <i class="fa-solid fa-check"></i>Alles Goedkeuren
                    </button>
                    <a class="btn btn-sm btn-info rounded" onclick="showAddWorkedHours.showModal()">
                        <i class="fa-solid fa-plus"></i>Toevoegen
                    </a>
                </div>
            </div>

            <div class="flex flex-col space-y-3 max-h-full overflow-y-auto">
                @if (Model.RegisteredHours.Any())
                {
                    @foreach (var Registered in Model.RegisteredHours)
                    {
                        @Html.Partial("Partials/_WorkedHours", Registered)
                    }
                }
            </div>
        </form>
    </div>

    <div class="flex flex-col space-y-5 w-1/4 bg-base-200 p-5 rounded mt-3 h-screen">
        <span class="font-bold text-xl">
            Exporteren - Week @Model.WeekNumber
        </span>

        @if (Model.AllWorkedHoursAreApproved)
        {
            <div class="flex flex-col space-y-3">
                <a class="btn btn-sm btn-success rounded" asp-controller="ExcelExport" asp-action="DownloadExcel" asp-route-date="@Model.Date">
                    <i class="fa-solid fa-download"></i> Exporteren
                </a>
            </div>
        }
        else
        {
            <div class="flex flex-col space-y-3">
                <span class="text-sm">Keur alle uren in week @Model.WeekNumber goed om te kunnen exporteren</span>
                <a class="btn btn-sm btn-disabled rounded">
                    <i class="fa-solid fa-download"></i> Exporteren
                </a>
            </div>
        }

    </div>
</div>
@Html.Partial("Modals/_CreateRegisteredHour", new Tuple<WorkedHoursViewModel, CreateRegisteredHourViewModel>(Model, new CreateRegisteredHourViewModel()))
@if (Model.RegisteredHours.Any())
{
    @foreach (var Registered in Model.RegisteredHours)
    {
        @Html.Partial("Modals/_EditRegisterdHour", Registered)
    }
}