Web/ViewModels/AbsenceViewModel.cs
using System.ComponentModel;
using Data.Enums;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels;
public class AbsenceViewModel : IValidatableObject
{
    public int Id { get; set; }
    public int EmployeeId { get; set; }

    [Required]
    [DisplayName("Vanaf datum")]
    public DateTime? StartDate { get; set; }

    [DisplayName("vanaf tijd")]
    public DateTime? StartTime { get; set; }
    
    [Required]
    [DisplayName("tot datum")]
    public DateTime? EndDate { get; set; }
    
    [DisplayName("tot tijd")]
    public DateTime? EndTime { get; set; }
    
    public EmployeeViewModel? Employee { get; set; }
    
    [MaxLength(100)]
    [DisplayName("Omschrijving")]
    public string? Description { get; set; }
    public AbsenceStatus? Status { get; set; }
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (EndDate.HasValue && StartTime.HasValue && EndDate.Value.Date == StartDate.Value.Date && EndTime <= StartTime)
        {
            yield return new ValidationResult("End time must be greater than the start time if on the same day.", new[] { nameof(EndTime) });
        }
        else if (EndDate.HasValue && EndDate < StartDate)
        {
            yield return new ValidationResult("End date must be greater than or equal to the start date.", new[] { nameof(EndDate) });
        }
    }
}

Web/ViewModels/PrognosisDayViewModel.cs
namespace Web.ViewModels;

using Data.Models;

public class PrognosisDayViewModel
{
    public IEnumerable<DailyPrognosis> Prognosis { get; set; }
    public IEnumerable<DailyExpectations> Expectations { get; set; }
    public Norm Norm { get; set; }
    public DateTime Date { get; set; }   
}

Web/ViewModels/PrognosisEditCreateViewModel.cs
using Data.Models;

namespace Web.ViewModels;

public class PrognosisEditCreateViewModel
{
    public int WeekNumber { get; set; }
    public DateTime Date { get; set; }
    
    public List<DailyPrognosis> Prognosis { get; set; }
    
    public List<DailyExpectations> Expectations { get; set; }
    public IEnumerable<Norm> Norms { get; set; }
}

Web/Controllers/AbsenceController.cs
using Data.Enums;
using Data.Interfaces;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Web.ViewModels;

namespace Web.Controllers;

public class AbsenceController : Controller
{
    private readonly IAbsenceRepository _absenceRepository;
    private readonly IEmployeeRepository _employeeRepository;

    public AbsenceController(IAbsenceRepository absenceRepository, IEmployeeRepository employeeRepository)
    {
        _absenceRepository = absenceRepository;
        _employeeRepository = employeeRepository;
    }

    // GET: Absence/Index
    public IActionResult Index()
    {
        Employee employee = _employeeRepository.GetEmployeeByEmail(User.Identity.Name);

        if (employee == null)
        {
            return NotFound();
        }

        var absences = _absenceRepository.GetAllAbsencesByEmployeeId(employee.Id)
            .Select(a => new AbsenceViewModel
            {
                Id = a.Id,
                EmployeeId = a.EmployeeId,
                StartDate = a.Start.Date,
                EndDate = a.End.Date,
                StartTime = a.Start,
                EndTime = a.End,
                Description = a.Description,
                Status = a.Status
            });

        var model = new EmployeeOverviewViewModel
        {
            Absences = absences
        };

        return View(model);
    }


    // GET: Absence/Create
    public IActionResult Create()
    {
        var model = new AbsenceViewModel()
        {
            Status = AbsenceStatus.Pending,
        };
        return View(model);
    }

    // POST: Absence/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(AbsenceViewModel model)
    {
        Employee employee = _employeeRepository.GetEmployeeByEmail(User.Identity.Name);
        
        if (ModelState.IsValid)
        {
            var newAbsence = new Absence
            {
                EmployeeId = employee.Id,
                Start = model.StartDate + model.StartTime?.TimeOfDay ?? (DateTime)model.StartDate,
                End = (model.EndDate + model.EndTime?.TimeOfDay) ?? (DateTime)model.EndDate,
                Description = model.Description,
                Status = (AbsenceStatus) model.Status
            };

            _absenceRepository.AddAbsence(newAbsence);

            return RedirectToAction("Index"); // Redirect to the index page or any other appropriate page
        }

        // If invalid
        return View("Create", model);
    }

    public IActionResult Delete(int id)
    {
        Absence absence = _absenceRepository.GetAbsenceById(id);

        if (absence == null)
        {
            return NotFound();
        }

        // Perform the deletion
        _absenceRepository.DeleteAbsence(id);
        return RedirectToAction("Index");
    }

    public IActionResult Evaluate()
    {
        var absences = _absenceRepository.GetAllAbsencesRequests();

        var absenceslist = absences.Select(a => new AbsenceViewModel
        {
            Id = a.Id,
            EmployeeId = a.EmployeeId,
            Employee = new EmployeeViewModel
            {
                FirstName = a.Employee.FirstName,
                LastName = a.Employee.LastName,
            },
            StartDate = a.Start.Date,
            EndDate = a.End.Date,
            StartTime = a.Start,
            EndTime = a.End,
            Description = a.Description,
            Status = a.Status,
        });

        return View(absenceslist);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Evaluate(int id, AbsenceStatus status)
    {
        Absence absence = _absenceRepository.GetAbsenceById(id);

        if (absence == null)
        {
            return NotFound();
        }

        absence.Status = status;
        _absenceRepository.Update(absence);

        return RedirectToAction("Evaluate");
    }

}

Web/Controllers/PrognosesController.cs
using System.Globalization;
using Data.Interfaces;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Utility.Extensions;
using Web.ViewModels;

namespace Web.Controllers;

[Authorize]
public class PrognosesController : Controller
{
    private readonly INormRepository _normRepository;
    private readonly IPrognosisRepository _prognosisRepository;

    public PrognosesController(IPrognosisRepository prognosisRepository, INormRepository normRepository)
    {
        _prognosisRepository = prognosisRepository;
        _normRepository = normRepository;
    }

    [HttpGet]
    public IActionResult Index(DateTime date)
    {
        var lastEightWeeks =  LastEightWeeks(date);

        PrognosisViewModel prognosisViewModel = new PrognosisViewModel
        {
            Prognosis = _prognosisRepository.GetWeeklyPrognosis(date),
            Norms =  _normRepository.GetAll(),
            Expectations = _prognosisRepository.GetWeeklyExpectations(date),
            WeekNumber = date.Week(),
            CurrentWeekNumber = DateTime.Now.Week(),
            DailyExpectationsLastEightWeeks =
                lastEightWeeks.ToDictionary(group => group.Key, group => group.AsEnumerable()),
            Date = date
        };

        return View(prognosisViewModel);
    }

    private IEnumerable<IGrouping<int, DailyExpectations>> LastEightWeeks(DateTime date)
    {
        List<DailyExpectations> lastEightWeeks = _prognosisRepository.GetLastEightWeeks(date);

        var groupedExpectations = lastEightWeeks.GroupBy(expectation =>
        {
         
            int weekNumber = expectation.Date.Week();
            return weekNumber;
        });

        return groupedExpectations;
    }


    [HttpGet]
    public IActionResult Create(DateTime date, PrognosisViewModel prognosisViewModel)
    {
        var dailyExpectationsList = DailyExpectationsList(prognosisViewModel);

        DateTime dateUsed = DateTime.Now;

        if (date >= dateUsed)
        {
            dateUsed = date;
        }
        else
        {
            dateUsed = prognosisViewModel.Date;
        }
        
        var prognosisCreateViewModel = new PrognosisEditCreateViewModel
        {
            WeekNumber = dateUsed.Week(),
            Expectations = dailyExpectationsList,
            Date = dateUsed.StartOfWeek(),
            Norms = _normRepository.GetAll()
        }; 

        return View(prognosisCreateViewModel);
    }

    private List<DailyExpectations> DailyExpectationsList(PrognosisViewModel prognosisViewModel)
    {
        string[] selectedWeeks;
        int[] selectedWeeksInt = new int[0];
        if (prognosisViewModel.SelectedWeeks != null)
        {
            selectedWeeks = prognosisViewModel.SelectedWeeks.Split(",");

            selectedWeeksInt = new int[selectedWeeks.Length];

            for (int i = 0; i < selectedWeeks.Length; i++)
            {
                if (int.TryParse(selectedWeeks[i], out int weekValue))
                {
                    selectedWeeksInt[i] = weekValue;
                }
            }
        }

        List<DailyExpectations> dailyExpectationsList = new List<DailyExpectations>();

        if (selectedWeeksInt.Length == 0)
        {
            for (int i = 0; i < 7; i++)
            {
                dailyExpectationsList.Add(new DailyExpectations { ExpectedColli = null, ExpectedCustomers = null });
            }
        }
        else
        {
            var groupedExpectations =  LastEightWeeks(prognosisViewModel.Date);
            
            var weeksToAverage = groupedExpectations.Where(group => selectedWeeksInt.Contains(group.Key));

            var flattenedData = weeksToAverage.SelectMany(group => group);

            var summedData = flattenedData
                .GroupBy(data => data.Date.DayOfWeek)
                .Select(group =>
                {
                    var dayOfWeek = group.Key;
                    var totalExpectedColli = group.Average(data => data.ExpectedColli) ?? 0;
                    var totalExpectedCustomers = group.Average(data => data.ExpectedCustomers) ?? 0;

                    return new
                    {
                        DayOfWeek = dayOfWeek,
                        TotalExpectedColli = totalExpectedColli,
                        TotalExpectedCustomers = totalExpectedCustomers
                    };
                })
                .ToList();

            summedData.ForEach(item =>
            {
                dailyExpectationsList.Add(new DailyExpectations
                {
                    ExpectedColli = (int)item.TotalExpectedColli,
                    ExpectedCustomers = (int)item.TotalExpectedCustomers
                });
            });
        }

        return dailyExpectationsList;
    }

    [HttpPost]
    public IActionResult Create(PrognosisEditCreateViewModel prognosisEditCreateViewModel)
    {
        _prognosisRepository.AddExpectations(prognosisEditCreateViewModel.Expectations);

        _prognosisRepository.GeneratePrognosis(prognosisEditCreateViewModel.Date, _normRepository.GetAll());

        return RedirectToAction("Index", "ManagerDashboard");
    }

    [HttpGet]
    public IActionResult Edit(DateTime date)
    {
        var expectations =  _prognosisRepository.GetWeeklyExpectations(date);
        var dailyPrognoses =  _prognosisRepository.GetWeeklyPrognosis(date);

        var prognosisCreateViewModel = new PrognosisEditCreateViewModel
        {
            WeekNumber = CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(
                date,
                CalendarWeekRule.FirstFourDayWeek,
                DayOfWeek.Monday
            ),
            Prognosis = dailyPrognoses.ToList(),
            Expectations = expectations.ToList(),
            Date = date.StartOfWeek(),
            Norms = _normRepository.GetAll()
        };

        return View(prognosisCreateViewModel);
    }

    [HttpPost]
    public IActionResult Edit(PrognosisEditCreateViewModel prognosisEditCreateViewModel)
    {
        _prognosisRepository.UpdateExpectations(prognosisEditCreateViewModel.Expectations);
        return View(prognosisEditCreateViewModel);
    }


    [HttpGet]
    public IActionResult EditPrognosis(DateTime date)
    {
        var prognosis = _prognosisRepository.GetWeeklyPrognosis(date);

        var prognosisCreateViewModel = new PrognosisEditCreateViewModel
        {
            WeekNumber = date.Week(),
            Prognosis = prognosis.ToList(),
            Date = date.StartOfWeek(),
            Norms = _normRepository.GetAll()
        };

        return View(prognosisCreateViewModel);
    }


    [HttpPost]
    public IActionResult EditPrognosis(PrognosisEditCreateViewModel prognosisEditCreateViewModel)
    {
        _prognosisRepository.Update(prognosisEditCreateViewModel.Prognosis);
        return View(prognosisEditCreateViewModel);
    }
}

Web/Controllers/ShiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data;
using Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Models;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Web.ViewModels;
using Data.Enums;
using Web.Controllers.Api;

namespace Web
{
    public class ShiftController : Controller
    {
        private readonly IShiftRepository _shiftRepository;
        private readonly IEmployeeRepository _employeeRepository;

        public ShiftController(IShiftRepository shiftRepository, IEmployeeRepository employeeRepository)
        {
            _shiftRepository = shiftRepository;
            _employeeRepository = employeeRepository;
        }

        // GET: Shift
        public IActionResult Index()
        {
            var shifts = _shiftRepository.GetBranchShifts();
            ShiftViewModel shiftViewModel = new ShiftViewModel
            {
                Shifts = shifts
            };
            return View(shiftViewModel);
        }

        // GET: Shift/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null) return NotFound();
            
            Shift shift = _shiftRepository.GetShift(id);
            
            if (shift == null) return NotFound();
            
            return View(shift);
        }

        // GET: Shift/Create
        public IActionResult Create()
        {
            var employees = _employeeRepository.GetAll();
            
            ShiftEditCreateViewModel shiftEditCreateViewModel = new ShiftEditCreateViewModel
            {
                Shift = new Shift(),
                Employees = employees.Select(employee => new EmployeeViewModel
                {
                    Id = employee.Id,
                    FirstName = employee.FirstName,
                    LastName = employee.LastName,
                    PhoneNumber = employee.PhoneNumber, 
                    Email = employee.Email,
                    DateOfBirth = employee.DateOfBirth,
                    BSN = employee.BSN,
                    PostalCode = employee.PostalCode,
                    City = employee.City,
                    HouseNumber = employee.HouseNumber,
                    Street = employee.Street,
                })
            };
            
            return View(shiftEditCreateViewModel);
        }

        // POST: Shift/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ShiftEditCreateViewModel shiftEditCreateViewModel)
        {
            
                foreach (var employee in shiftEditCreateViewModel.Employees)
                {
                    Shift shift = new Shift
                    {
                        EmployeeId = employee.Id,
                        Start = shiftEditCreateViewModel.Shift.Start,
                        End = shiftEditCreateViewModel.Shift.End,
                        BranchId = 1
                    };
                    _shiftRepository.Add(shift);
                }
                return RedirectToAction(nameof(Index));
            return View(shiftEditCreateViewModel);
        }

        // GET: Shift/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();

            Shift shift = _shiftRepository.GetShift(id);
            
            if (shift == null) return NotFound();
                
            return View(shift);
        }

        // POST: Shift/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id,BranchId,Start,End")] Shift shift)
        {
            _shiftRepository.UpdateShift(shift);
            return View(shift);
        }

        // GET: Shift/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound();
            
            Shift shift = _shiftRepository.GetShift(id);

            return View(shift);
        }

        // POST: Shift/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Shift shift)
        {

            _shiftRepository.DeleteShift(shift);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Views/Shared/Partials/_Absence.cshtml
@model Web.ViewModels.AbsenceViewModel

<div class="rounded-lg bg-gray-300 flex">
    <div class="rounded-s-lg w-5 bg-jumbo-yellow"></div>
    <div class="flex flex-col p-2">
        @if ((bool)ViewData["Evaluate"])
        {
            <span class="font-semibold text-sm">@Model.Employee.FirstName @Model.Employee.LastName</span>
        }
        <div class="flex space-x-2">
            <div>
                <span class="font-bold text-md font-semibold">
                    @if (Model.StartDate != Model.EndDate)
                    {
                        @($"{Model.StartDate?.DateNameShort()} - {Model.EndDate?.DateNameShort()}")
                    }
                    else
                    {
                        @Model.StartDate?.DateName()
                    }
                </span>
                @if (Model.StartDate == Model.EndDate)
                {
                    <div class="font-bold text-xs">
                        @if (Model.StartTime?.Time() == "00:00" && Model.EndTime?.Time() == "00:00")
                        {
                            <span>De hele dag</span>
                        }
                        else
                        {
                            @($"{Model.StartTime?.Time()} - {Model.EndTime?.Time()}")
                        }
                    </div>
                }
                <div class="font-medium text-xs">
                    @Model.Description
                </div>
            </div>
        </div>
    </div>
    @if ((bool)ViewData["Evaluate"])
    {
        <div class="ml-auto flex items-center mr-5">
            <div class="flex space-x-3">
                <i class="fa-solid fa-circle-check text-green-600" onclick="showAccept@(Model.Id).showModal()"></i>
                <i class="fa-solid fa-circle-xmark text-red-600" onclick="showDecline@(Model.Id).showModal()"></i>
            </div>
        </div>
    }
    else
    {
        <div class="ml-auto flex items-center mr-5">
            <div style="margin-right: 15px;">
                <a asp-controller="Absence" asp-action="Delete" asp-route-id="@Model.Id">
                    <i class="fa-solid fa-trash-can" style="color: #ff0000;"></i>
                </a>
            </div>
            <span class="font-bold text-md font-semibold align-middle ml-2">
                @switch (Model.Status)
                {
                    case AbsenceStatus.Declined:
                        <i class="fa-solid fa-circle-xmark" style="color: #ff4000;"></i>
                        break;
                    case AbsenceStatus.Approved:
                        <i class="fa-solid fa-circle-check" style="color: #00ff00;"></i>
                        break;
                    case AbsenceStatus.Pending:
                        <i class="fa-solid fa-circle-dot" style="color: #ffb400;"></i>
                        break;
                }
            </span>
        </div>
    }
</div>
@Html.Partial("Modals/_EvaluateDecisionDecline")
@Html.Partial("Modals/_EvaluateDecisionAccept")

Web/Views/Shared/Partials/_DaySelector.cshtml
@model Web.ViewModels.WorkedHoursViewModel
<div class="flex justify-between items-center text-center space-x-3 w-fit">
    <a class="btn btn-sm btn-warning rounded" asp-controller="WorkedHours" asp-action="Index" asp-route-date="@Model.Date.AddDays(-1)">
        <i class="fa-solid fa-chevron-left"></i>
    </a>
    <div class="flex flex-col text-center">
        <h3 class="text-sm font-bold">Week @Model.WeekNumber - @Model.Date.Year</h3>
        <p class="text-xs">
            @Model.Date.ToString("d MMMM", new CultureInfo("nl-NL"))
        </p>
    </div>

    @if (Model.Date.Date == DateTime.Now.Date)
    {
        <a class="btn btn-sm btn-disabled rounded">
            <i class="fa-solid fa-chevron-right"></i>
        </a>
    }
    else
    {
        <a class="btn btn-sm btn-warning rounded"
           asp-controller="WorkedHours"
           asp-action="Index"
           asp-route-date="@Model.Date.AddDays(1)">
            <i class="fa-solid fa-chevron-right"></i>
        </a>
    }
</div>

Web/Views/Shared/Partials/_ExpectationsEditCreate.cshtml
@model Web.ViewModels.PrognosisEditCreateViewModel

    <div class="bg-base-200 rounded p-3 shadow">
        <table class="table-lg rounded border">
            <tbody class="rounded">
            <input type="hidden" asp-for="Date" value="@Model.Date"/>
            <tr class="border border-black">
                <th>
                    Verwachting
                </th>
                @for (int i = 0; i < 7; i++)
                {
                    <input type="hidden" value="@Model.Date.AddDays(i)" asp-for="Expectations[i].Date"/>
                    <input type="hidden" asp-for="Expectations[i].Id"/>
                    <input type="hidden" asp-for="Expectations[i].Branch"/>
                    <input type="hidden" value="1" asp-for="Expectations[i].BranchId"/>
                    var currentDate = Model.Date.AddDays(i);
                    <td class="uppercase font-semibold">
                        @currentDate.ToString("ddd", new CultureInfo("nl-NL"))
                        @currentDate.ToString("dd-MM", new CultureInfo("nl-NL"))
                    </td>
                }
            </tr>
            <tr class="border border-black">
                <th>Colli's</th>
                @for (int i = 0; i < 7; i++)
                {
                    <td>
                        <div class="form-group">
                            <input asp-for="@Model.Expectations[i].ExpectedColli" type="number" required min="0"
                                   class="form-control input input-xs input-bordered w-14">

                        </div>
                    </td>
                }
            </tr>
            <tr class="border border-black">
                <th>Klanten</th>
                @for (int i = 0; i < 7; i++)
                {
                    <td>
                        <div class="form-group">
                            <input asp-for="@Model.Expectations[i].ExpectedCustomers" type="number" required min="0"
                                   class="form-control input input-xs input-bordered w-14">
                        </div>
                    </td>
                }
            </tr>
            </tbody>
        </table>
    </div>
    

Web/Views/Shared/Partials/_ExpectationsTable.cshtml
@model Web.ViewModels.PrognosisViewModel
<div class="bg-base-200 rounded p-3 shadow @(Model.Expectations.Any() ? "" : "hidden")">
    <table class="table-lg rounded border">
        <tbody class="rounded">
        <tr class="border border-black">
            <th>
                Verwachting
            </th>
            @foreach (var item in Model.Expectations)
            {
                <td class="uppercase font-semibold">
                    @item.Date.ToString("ddd", new CultureInfo("nl-NL"))
                    @item.Date.ToString("dd-MM", new CultureInfo("nl-NL"))
                </td>
            }
        </tr>
        <tr class="border border-black">
            <th>Colli's</th>
            @foreach (var item in Model.Expectations)
            {
                <td>
                    <p>@item.ExpectedColli</p>
                </td>
            }
        </tr>
        <tr class="border border-black">
            <th>Klanten</th>
            @foreach (var item in Model.Expectations)
            {
                <td>
                    <p>@item.ExpectedCustomers</p>
                </td>
            }
        </tr>
        </tbody>
    </table>
</div>

Web/Views/Shared/Partials/_PrognosisEditCreateTable.cshtml
@using Microsoft.AspNetCore.Razor.Language
@model Web.ViewModels.PrognosisEditCreateViewModel
<form asp-action="EditPrognosis" method="post" asp-controller="Prognoses">
    <div class="bg-base-200 rounded p-3 shadow">
        <table class="table-lg rounded border">
            <tbody class="rounded">
            <tr class="border border-black">
                <th>
                    Afdeling
                </th>
                @for (int i = 0; i < Model.Prognosis.Count; i++)
                
                {
                    <input type="hidden" asp-for="Prognosis[i].Id"/>
                    <input type="hidden" asp-for="Prognosis[i].Department"/>
                    <input type="hidden" asp-for="Prognosis[i].Date"/>
                    <input type="hidden" asp-for="Prognosis[i].Branch"/>
                    <input type="hidden" asp-for="Prognosis[i].BranchId"/>
                    if (Model.Prognosis[i].Department == Departments.Checkout)
                    {
                        <td class="uppercase font-semibold">
                            @Model.Prognosis[i].Date.ToString("ddd", new CultureInfo("nl-NL"))
                            @Model.Prognosis[i].Date.ToString("dd-MM", new CultureInfo("nl-NL"))
                        </td>
                    }
                }
            </tr>
            <tr class="border border-black">
                <th>Vers</th>
                @for (int i = 0; i < Model.Prognosis.Count; i++)
                {
                    if (Model.Prognosis[i].Department == Departments.Fresh)
                    {
                        var workers = Model.Prognosis[i].NumberOfHours / 8;
                        <td>
                            <input class="input input-xs input-bordered w-14" type="number" asp-for="Prognosis[i].NumberOfHours" value="@Model.Prognosis[i].NumberOfHours"/>
                            <p class="text-green-600">@workers pers.</p>
                        </td>
                    }
                }
            </tr>
            <tr class="border border-black">
                <th>Kassa</th>
                @for (int i = 0; i < Model.Prognosis.Count; i++)
                {
                    if (Model.Prognosis[i].Department == Departments.Checkout)
                    {
                        var workers = Model.Prognosis[i].NumberOfHours / 8;
                        <td>
                            <input class="input input-xs input-bordered w-14" type="number" asp-for="Prognosis[i].NumberOfHours" value="@Model.Prognosis[i].NumberOfHours"/>
                            <p class="text-green-600">@workers pers.</p>
                        </td>
                    }
                }
            </tr>
            <tr class="border border-black">
                <th>Vakkenvullen</th>
                @for (int i = 0; i < Model.Prognosis.Count; i++)
                {
                    if (Model.Prognosis[i].Department == Departments.Dkw)
                    {
                        var workers = Model.Prognosis[i].NumberOfHours / 8;
                        <td>
                            <input class="input input-xs input-bordered w-14" type="number" asp-for="Prognosis[i].NumberOfHours" value="@Model.Prognosis[i].NumberOfHours"/>
                            <p class="text-green-600">@workers pers.</p>
                        </td>
                    }
                }
            </tr>
            </tbody>
        </table>
    </div>
    <button type="submit" class="btn btn-sm btn-primary mt-3 self-end">Opslaan</button>
</form>

Web/Views/Shared/Partials/_WeekSelector.cshtml
@model Web.ViewModels.PrognosisViewModel
<div class="flex justify-between items-center text-center space-x-3 w-fit">
    <a class="btn btn-sm btn-info rounded text-white @(Model.WeekNumber != Model.CurrentWeekNumber ? "" : "hidden")" asp-controller="Prognoses" asp-action="Index" asp-route-date="@DateTime.Now">
        <i class="fa-solid fa-calendar-week"></i>
    </a>
    <a class="btn btn-sm btn-warning rounded" asp-controller="Prognoses" asp-action="Index" asp-route-date="@Model.Date.AddDays(-7)">
        <i class="fa-solid fa-chevron-left"></i>
    </a>
    <div class="flex flex-col text-center">
        <h3 class="text-sm font-bold">Week @Model.WeekNumber - @Model.Date.Year</h3>
        <p class="text-xs">
            @Model.Date.AddDays(-(int)Model.Date.DayOfWeek + 1).ToString("d MMMM", new CultureInfo("nl-NL"))
            -
            @Model.Date.AddDays(7 - (int)Model.Date.DayOfWeek).ToString("d MMMM", new CultureInfo("nl-NL"))
        </p>
    </div>
    <a class="btn btn-sm btn-warning rounded" asp-controller="Prognoses" asp-action="Index" asp-route-date="@Model.Date.AddDays(7)">
        <i class="fa-solid fa-chevron-right"></i>
    </a>

    <button class="btn btn-sm btn-secondary rounded text-white @(Model.Prognosis.Any() ? "hidden" : "")" onclick="showPrognoseCreationOptions.showModal()">
        <i class="fa-solid fa-plus"></i> Toevoegen
    </button>
    <a class="btn btn-sm btn-neutral rounded text-white @(Model.Prognosis.Any() ? "" : "hidden")" asp-controller="Prognoses" asp-action="EditPrognosis" asp-route-date="@Model.Date">
        <i class="fa-solid fa-clock"></i> Bewerken uren
    </a>
    <a class="btn btn-sm btn-neutral rounded text-white @(Model.Expectations.Any() ? "" : "hidden")" asp-controller="Prognoses" asp-action="Edit" asp-route-date="@Model.Date">
        <i class="fa-solid fa-pen-to-square"></i> Bewerken verwachtingen
    </a>
</div>