Web/ViewModels/SchoolHoursViewModel.cs
using Data.Models;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;


namespace Web.ViewModels;

public class SchoolHoursViewModel
{
    public List<SchoolHours>? SchoolHours { get; set; }
}

Web/Controllers/SchoolHoursController.cs
using Data.Enums;
using Data.Interfaces;
using Data.Models;
using Data.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.ViewModels;

namespace Web.Controllers
{
    [Authorize]
    public class SchoolHoursController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly ISchoolHoursRepository _schoolHoursRepository;
        public SchoolHoursController(IEmployeeRepository employeeRepository, ISchoolHoursRepository schoolHoursRepository)
        {
            _employeeRepository = employeeRepository;
            _schoolHoursRepository = schoolHoursRepository;
        }
        // GET: HomeController
        public IActionResult Index()
        {
            // Get the logged-in user
            var loggedInEmployee = _employeeRepository.GetEmployeeByEmail(User.Identity.Name); //EmployeeId
            var existingSchoolHours = _schoolHoursRepository.GetAllHoursOfEmployee(loggedInEmployee.Id);
            List<SchoolHours> SchoolHoursAllDays = new List<SchoolHours>();
            foreach (var day in Enum.GetValues(typeof(WeekDays)).Cast<WeekDays>().Where(d => d != WeekDays.Saturday && d != WeekDays.Sunday)) // loop all days except saturday and sunday
            {
                var schoolHour = new SchoolHours
                {
                    DayOfWeek = day,
                    EmployeeId = loggedInEmployee.Id
                };
                SchoolHoursAllDays.Add(schoolHour);
            }

            // Merge the existing and  school hours dummys based on the day of the week
            List<SchoolHours> mergedSchoolHours = existingSchoolHours
                .Concat(SchoolHoursAllDays)
                .GroupBy(sh => sh.DayOfWeek)
                .Select(group => group.First()).OrderBy(sh => sh.DayOfWeek)
                .ToList();

            var viewModel = new SchoolHoursViewModel
            {
                SchoolHours = mergedSchoolHours,
            };

            return View(viewModel);
        }

        // GET: HomeController/Edit/5
        public IActionResult EditCreate(int id)
        {
            var loggedInEmployee = _employeeRepository.GetEmployeeByEmail(User.Identity.Name); //EmployeeId

            var existingSchoolHours = _schoolHoursRepository.GetAllHoursOfEmployee(loggedInEmployee.Id);
            List<SchoolHours> SchoolHoursAllDays = new List<SchoolHours>();
            foreach (var day in Enum.GetValues(typeof(WeekDays)).Cast<WeekDays>().Where(d => d != WeekDays.Saturday && d != WeekDays.Sunday)) // loop all days except saturday and sunday
            {
                var schoolHour = new SchoolHours
                {
                    DayOfWeek = day,
                    EmployeeId = loggedInEmployee.Id
                };
                SchoolHoursAllDays.Add(schoolHour);
            }

            // Merge the existing and  school hours dummys based on the day of the week
            List<SchoolHours> mergedSchoolHours = existingSchoolHours
                .Concat(SchoolHoursAllDays)
                .GroupBy(sh => sh.DayOfWeek)
                .Select(group => group.First()).OrderBy(sh => sh.DayOfWeek)
                .ToList();

            var viewModel = new SchoolHoursViewModel
            {
                SchoolHours = mergedSchoolHours,
            };

            return View(viewModel);
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        public IActionResult EditCreate(SchoolHoursViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Filter out unnessecary SchoolHours
                var nonZeroHours = model.SchoolHours.Where(sh => sh.Hours != 0 || sh.Id != 0).ToList();

                // Separate existing and new SchoolHours
                var zeroHoursLeft = nonZeroHours.Where(sh => sh.Hours == 0).ToList(); // 0 hours means delete
                var existingHours = nonZeroHours.Where(sh => sh.Id != 0 && sh.Hours != 0).ToList();
                var newHours = nonZeroHours.Where(sh => sh.Id == 0).ToList();

                // Delete SchoolHours
                _schoolHoursRepository.DeleteSchoolHours(zeroHoursLeft);
                // Update existing SchoolHours
                _schoolHoursRepository.UpdateSchoolHours(existingHours);
                // Create new SchoolHours
                _schoolHoursRepository.CreateSchoolHours(newHours);

                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Web/Views/SchoolHours/EditCreate.cshtml
@model Web.ViewModels.SchoolHoursViewModel

@{
    ViewBag.Title = "title";
    Layout = "_EmployeeLayout";
}

<div class="flex flex-col space-y-5">
    <div class="flex flex-col">
        <span class="font-bold text-xl">
            Schooluren
        </span>
        <small class="font-light text-sm">Les uren excl. pauze, tussenuren</small>
    </div>
    
    <form asp-action="EditCreate" method="post" class="space-y-3">
        @foreach (var schoolHour in Model.SchoolHours)
        {
            var i = (int)schoolHour.DayOfWeek;
            <input asp-for="@Model.SchoolHours[i].Id" type="hidden" class="form-control"/>
            <input asp-for="@Model.SchoolHours[i].DayOfWeek" type="hidden" class="form-control"/>
            <input asp-for="@Model.SchoolHours[i].EmployeeId" type="hidden" class="form-control"/>
            <div class="form-control w-full ">
                <div class="label">
                    <span class="label-text">
                        @schoolHour.DayOfWeek
                    </span>
                </div>
                <input asp-for="@Model.SchoolHours[i].Hours" type="number" min="0" max="24" class="input w-full"/>
                @Html.ValidationMessageFor(Model => Model.SchoolHours[i].Hours, "", new { @class = "text-danger" })
            </div>
        }
        <button type="submit" class="btn btn-sm btn-primary mt-3 self-end">Opslaan</button>
    </form>
</div>

Web/Views/SchoolHours/Index.cshtml
@model Web.ViewModels.SchoolHoursViewModel
@{
    ViewBag.Title = "title";
    Layout = "_EmployeeLayout";
}

<div class="flex flex-col space-y-5">
    <div class="flex justify-between">
        <span class="font-bold text-xl">
            Schooluren
        </span>
        <a asp-controller="SchoolHours" asp-action="EditCreate" class="btn btn-sm btn-primary">
            Bewerken
        </a>
    </div>

    @if (Model.SchoolHours != null && Model.SchoolHours.Any())
    {
        @foreach (var schoolHour in Model.SchoolHours)
        {
            <div class="flex flex-col bg-gray-200 rounded p-3">
                <span class="font-semibold text-md">@schoolHour.DayOfWeek</span>
                <span>@schoolHour.Hours uren</span>
            </div>
        }
    }
    else
    {
        <p>Je hebt nog geen school uren opgegeven</p>
    }
</div>